In [13]:
'''Create a "Matrix Operations Tool" using Python and the NumPy library.
The application should allow users to input matrices and perform operations like addition, subtraction, multiplication, transpose, and determinant calculation.
Include an interactive interface to display results in a structured format.'''
# FIRST TASK
import numpy as np
def display_matrix():
    rows=int(input("enter the rows"))
    column=int(input("enter the column"))
    matrix=[]
    for i in range(rows):
        row=list(map(int,input(f"{i+1}").split()))
        matrix.append(row)
    return np.array(matrix)
A=display_matrix()        
B=display_matrix()


   

enter the rows 3
enter the column 3
1 2 4 5
2 1 3 5
3 7 8 5
enter the rows 3
enter the column 3
1 1 9 87
2 3 5 76
3 1 2 43


In [14]:
# TWO MATRIX ADDITION
def addition(A,B):
    if A.shape==B.shape:
        return np.add(A,B)
    else :
        print("MATRIX A AND B SHOULD BE SAME SHAPE FOR ADDITION")
        return None
    display_matrix()
addition(A,B)

array([[ 3, 13, 92],
       [ 4,  8, 81],
       [ 8, 10, 48]])

In [15]:
# TWO MATRIX SUBTRACTION
def subtraction(A,B):
    if A.shape==B.shape:
        return np.subtract(A,B)
    else :
        print("MATRIX A AND B SHOULD BE SAME SHAPE FOR SUBTRACTION")
        return None
    display_matrix()
subtraction(A,B)

array([[  1,  -5, -82],
       [ -2,  -2, -71],
       [  6,   6, -38]])

In [16]:
# TWO MATRIX MULTIPLY
def multiply(A,B):
    if A.shape==B.shape:
        return np.dot(A,B)
    else :
        print("MATRIX A AND B SHOULD BE SAME FOR MULTIPLICATION")
        return None
    display_matrix()
multiply(A,B)

array([[  19,   48,  693],
       [  15,   34,  530],
       [  36,  113, 1432]])

In [17]:
# TRANSPOSE OF A MATRIX
def transpose(A):
    return np.transpose(A)
transpose(A)

array([[2, 1, 7],
       [4, 3, 8],
       [5, 5, 5]])

In [18]:
# DETERMINANT OF A MATRIX
def determinant(A):
    if A.shape==B.shape:
        return np.linalg.det(A)
    else :
        print("MATRIX A SHOULD BE A SQUARE ")
        return None
    display_matrix()
determinant(A)

4.999999999999998

In [19]:
# INVERSE OF A MATRIX
def inverse(A):
    return np.linalg.inv(A)
inverse(A)

array([[-5. ,  4. ,  1. ],
       [ 6. , -5. , -1. ],
       [-2.6,  2.4,  0.4]])

In [20]:
# RANK OF A MATRIX
def rank(A):
    return np.linalg.matrix_rank(A)
rank(A)

3

In [21]:
# overall structured format for interactive output
def main():
    print("matrix operation tool")
    choice=(input("enter the choice"))
    if choice=="1":
        return f"ADDITION{addtion(A,B)}"
    elif choice=="2":
        return f"SUBTRACTION{subtraction(A,B)}"
    elif choice=="3":
        return f"MULTIPLY{multiply(A,B)}"
    elif choice=="4":
        return f"TRANSPOSE{transpose(A)}"
    elif choice=="5":
        return f"DETERMINANT{determinant(A)}"
    elif choice=="6":
        return f"INVERSE{inverse(A)}"
    elif choice=="7":
        return f"RANK{rank(A)}"
    else:
        print("INVALID INPUT")
main()        


matrix operation tool


enter the choice 6


'INVERSE[[-5.   4.   1. ]\n [ 6.  -5.  -1. ]\n [-2.6  2.4  0.4]]'